
export const LOGIN = 'LOGIN'

export const LOGOUT = 'LOGOUT'

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'

export const UPDATE_USER_STATE = 'UPDATE_USER_STATE'

export const UPDATE_INCREMENT_COUNT = 'UPDATE_INCREMENT_COUNT'
export const UPDATE_DECRMENT_COUNT = 'UPDATE_DECRMENT_COUNT'

